Repository CARTAvis/carta-backend, pull requests merged in 2024-01, with the labels that each got.

#1308 skip running casa_data_autoupdate if checking version
  scripts/carta
Labels: awaiting testing

#1320 Compatibility with carta-casacore updated to CASA 6.6.0
  CHANGELOG.md
  CMakeLists.txt
  src/ImageData/CartaFitsImage.cc
  src/ImageGenerators/Image2DConvolver.tcc
  src/ImageGenerators/ImageMoments.tcc
  src/Main/Main.cc
  src/Region/LineBoxRegions.cc
  src/Region/Region.cc
  src/Region/RegionHandler.cc
Labels: code maintenance, awaiting merge

#1351 Bump version to 5.0.0-dev
  src/Util/App.h
Labels: awaiting code review
