Repository CARTAvis/carta-backend, pull requests merged in 2024-06, with the labels that each got.

#1376 Fix incorrect parsing of the ATCA FITS header
  CHANGELOG.md
  src/FileList/FileExtInfoLoader.cc
Labels: awaiting merge

#1355 Support PV images from polyline region
  CHANGELOG.md
  src/ImageGenerators/PvGenerator.cc
  src/ImageGenerators/PvGenerator.h
  src/Region/RegionHandler.cc
  test/TestPvGenerator.cc
Labels: requiring frontend, awaiting merge

#1338 Add custom prefix to all HTTP server URLs
  src/HttpServer/HttpServer.cc
  src/HttpServer/HttpServer.h
  src/Main/Main.cc
  src/Main/ProgramSettings.cc
  src/Main/ProgramSettings.h
Labels: awaiting testing, awaiting code review
