Repository CARTAvis/carta-backend, pull requests merged in 2025-06, with the labels that each got.

#1417 Allow scripting to find resumed sessions
  CHANGELOG.md
  src/Session/SessionManager.cc
  src/Session/SessionManager.h
Labels: awaiting merge

#1438 Check for FITS BEAMS table before removing single beam not in headers
  CHANGELOG.md
  src/FileList/FileExtInfoLoader.cc
  src/FileList/FileExtInfoLoader.h
  src/ImageData/FitsLoader.cc
  src/ImageData/FitsLoader.h
Labels: awaiting merge

#1440 Changing the SessionManager OnMessage Switch statement to handler functions
  src/Session/Session.cc
  src/Session/SessionManager.cc
  src/Session/SessionManager.h
  src/Util/Message.cc
  src/Util/Message.h
  src/Util/Message.tcc
Labels: awaiting merge

#1467 Prevent duplicate sync IDs
  CHANGELOG.md
  src/Session/Session.h
Labels: awaiting merge

#1443 Fix region import from top-level directory
  CHANGELOG.md
  src/FileList/FileListHandler.cc
  src/Session/Session.cc
  test/TestFileList.cc
Labels: awaiting testing, awaiting code review

#1469 Yuhsuan/fitting init val
  CHANGELOG.md
  CMakeLists.txt
  src/Frame/Frame.h
  src/ImageFitting/ImageFitter.cc
  src/ImageFitting/ImageFitter.h
  src/ImageFitting/InitialValueCalculator.cc
  src/ImageFitting/InitialValueCalculator.h
  src/ImageFitting/Util.h
  test/TestImageFitting.cc
Labels: requiring frontend, awaiting merge
